name: Deploy Payments App

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:       
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/payments-github-role
          aws-region: us-east-2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2.1.7

      - name: Build and push Docker image to ECR
        run: |
          docker build -f apps/payments/Dockerfile -t ${{ secrets.PAYMENTS_ECR_REPO }}:latest apps/payments/
          docker push ${{ secrets.PAYMENTS_ECR_REPO }}:latest

      - name: Fetch ECS Task Definition
        run: |
          aws ecs describe-task-definition --task-definition payments-task-family --query taskDefinition > payments-task-family.json

      - name: Update task definition
        id: updated-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1.9.0
        with:
          task-definition: payments-task-family.json
          container-name: payments-container
          image: ${{ secrets.PAYMENTS_ECR_REPO }}:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.6.3
        with:
          task-definition: ${{ steps.updated-task.outputs.task-definition }}
          cluster: ${{ vars.PAYMENTS_CLUSTER }}
          service: ${{ vars.PAYMENTS_SERVICE }}
          wait-for-service-stability: true
