name: Apply Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform-github-role
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: 1.16.3

      - name: Initiate Terraform
        run: terraform init
        working-directory: terraform/

      - name: Apply infrastructure
        run: terraform apply -auto-approve
        working-directory: terraform/
